apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: spring-cloud-gateway-for-kubernetes
spec:
  title: Spring Cloud Gateway for Kubernetes
  description: A workshop for using Spring Cloud Gateway for Kubernetes
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/ccollicutt/spring-cloud-gateway-learning-center
  content:
    files: github.com/ccollicutt/spring-cloud-gateway-learning-center?ref=main
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
